### ISSUE TITLE
How to do inference using SMPL-H model?

### ISSUE THREAD

**Issue by luyr** [fantaosha/SCOPE#2]
Thank you for your great work!
I've seen that you have showed the results of applying your method on smpl-h. Could you please tell me how to use smpl-h for inference rather than smpl.
THANK YOU VERY MUCH !!!!!

**Comment by fantaosha** [comment]
Hello,

1- Follow [SMPL.h](https://github.com/fantaosha/SCOPE/blob/master/C%2B%2B/scope/model/SMPL.h) and [SMPL.cpp](https://github.com/fantaosha/SCOPE/blob/master/C%2B%2B/scope/model/SMPL.cpp) to define the model info for SMPL-H.

2- Follow [SMPLify.h](https://github.com/fantaosha/SCOPE/blob/master/C%2B%2B/scope/optimizer/SMPLify.h) and [SMPLify.cpp](https://github.com/fantaosha/SCOPE/blob/master/C%2B%2B/scope/optimizer/SMPLify.cpp) to define the optimizer.

3- You might also need to train joint priors for the hand.
