### ISSUE TITLE
 error: ‘Matrix3X’ is not a member of ‘Eigen’

### ISSUE THREAD

**Issue by Allen-lz** [fantaosha/SCOPE#4]
This is a wonderful job! 
The following error occurred during compilation:
SCOPE/C++/scope/utils/Setup.cpp:195:36: error: ‘Matrix3X’ is not a member of ‘Eigen’; did you mean ‘Matrix3Xd’?
  195 |   Measurements = Eigen::Map<Eigen::Matrix3X<double>>(
         |                                    ^~~~~~~~
         |                                    Matrix3Xd

Excuse me, is there something wrong with the Eigen version I installed?
What is the correct Eigen version?

**Comment by fantaosha** [comment]
Hello, you can either use `Eigen 3.4` or replace `Eigen::Matrix3X<double>` with `Eigen::Matrix3Xd`.

> This is a wonderful job! The following error occurred during compilation: SCOPE/C++/scope/utils/Setup.cpp:195:36: error: ‘Matrix3X’ is not a member of ‘Eigen’; did you mean ‘Matrix3Xd’? 195 | Measurements = Eigen::Map<Eigen::Matrix3X>( | ^~~~~~~~ | Matrix3Xd
> 
> Excuse me, is there something wrong with the Eigen version I installed? What is the correct Eigen version?
